# docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

version: '3.4'
services:
  ollama:
    image: ollama/ollama:0.1.32
    container_name: ollama
    restart: always
    command: ["serve"] 
    ports:
      - "11434:11434"
    volumes:
      - ${OPT_STACKS_DIR}\ollama\.ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "1"
              capabilities: [gpu]