version: "3.8"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    ports:
      - 3001:3000
    environment:
      - OPENAI_API_KEY=
      - GOOGLE_API_KEY=
      - CODE=
      - BASE_URL=
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=